tableau/tabcmd

.gitignore, contributing.md, setup.cfg, setup.py, tabcmd/commands/commands.py, tabcmd/commands/user/user_command.py, tests/test_user_utils.py
I added a bunch of test cases - some of them seem to me to expose errors in the existing behavior. I thought this would get it clearly documented and then we can figure out what we want to change.
It would probably help to cross-check the behavior against old tabcmd, too.
=> test cases for user utils, updated logic for calculating user role 

tabcmd/commands/commands.py, tabcmd/commands/datasources_and_workbooks/delete_command.py, tabcmd/commands/extracts/create_extracts_command.py, tabcmd/commands/extracts/refresh_extracts_command.py, tabcmd/commands/help/help_command.py, tabcmd/parsers/create_group_parser.py, tabcmd/parsers/decrypt_extracts_parser.py, tabcmd/parsers/delete_group_parser.py, tabcmd/parsers/delete_site_parser.py, tabcmd/parsers/edit_site_parser.py, tabcmd/parsers/encrypt_extracts_parser.py, tabcmd/parsers/export_parser.py, tabcmd/parsers/reencrypt_parser.py, tabcmd/parsers/runschedule_parser.py
flake8 identifies all of these as unused - figured an easy cleanup
=> Removed unused imports, variables, functions

.github/workflows/generate-metadata.yml, mypy.ini, setup.py, tabcmd/commands/commands.py, tests/commands/test_geturl_utils.py, tests/e2e/setup_e2e.py, tests/e2e/tests_integration.py
Very barebones introduction - no annotations, but clean runs on all existing files.
=> Add mypy type checking

tabcmd/commands/constants.py, tabcmd/commands/group/create_group_command.py, tabcmd/commands/project/create_project_command.py, tabcmd/commands/site/create_site_command.py, tabcmd/execution/parent_parser.py, tests/commands/test_run_commands.py
Half the time I just want the thing to exist, I don't care if I am creating it new or it was there already.
Added a test for each command.
=> allow createproject/site/group to return happy if item already exists

.gitignore, tabcmd/commands/extracts/refresh_extracts_command.py, tabcmd/execution/global_options.py
fix the destination variable declaration in global options
add short name options for refresh_extracts
=> fix arg names for two extract commands

.gitignore, tabcmd/commands/auth/session.py, tests/commands/test_credential_file.txt, tests/commands/test_session.py, tests/e2e/setup_e2e.py, tests/e2e/tests.py
* Note: We have assumed that the password file can only contain one line. We must handle the cases where there could be multiple PATs and or at least mention this case in docs. 
https://github.com/tableau/tabcmd/issues/98
=> Fixed password file throws I/O Exception bug 

tabcmd/commands/auth/login_command.py, tabcmd/commands/auth/logout_command.py, tabcmd/commands/auth/session.py, tabcmd/commands/datasources_and_workbooks/delete_command.py, tabcmd/commands/datasources_and_workbooks/export_command.py, tabcmd/commands/datasources_and_workbooks/get_url_command.py, tabcmd/commands/datasources_and_workbooks/publish_command.py, tabcmd/commands/datasources_and_workbooks/runschedule_command.py, tabcmd/commands/extracts/create_extracts_command.py, tabcmd/commands/extracts/decrypt_extracts_command.py, tabcmd/commands/extracts/delete_extracts_command.py, tabcmd/commands/extracts/encrypt_extracts_command.py, tabcmd/commands/extracts/reencrypt_extracts_command.py, tabcmd/commands/extracts/refresh_extracts_command.py, tabcmd/commands/group/create_group_command.py, tabcmd/commands/group/delete_group_command.py, tabcmd/commands/project/create_project_command.py, tabcmd/commands/project/delete_project_command.py, tabcmd/commands/project/publish_samples_command.py, tabcmd/commands/site/create_site_command.py, tabcmd/commands/site/delete_site_command.py, tabcmd/commands/site/edit_site_command.py, tabcmd/commands/site/list_sites_command.py, tabcmd/commands/user/add_users_command.py, tabcmd/commands/user/create_site_users.py, tabcmd/commands/user/create_users_command.py, tabcmd/commands/user/delete_site_users_command.py, tabcmd/commands/user/remove_users_command.py, tests/e2e/tests_integration.py
instead of always showing the class that created the logger
pulling this into a standalone CR because it touches so many files.
=> change log to show current source file

.github/workflows/publish-pypi.yml, .github/workflows/run-tests.yml, pyproject.toml, src/commands/site/delete_site_command.py, src/commands/site/list_sites_command.py
c:\dev\tabcmd2>python -m tabcmd listsites
INFO:  Read the Tableau Server password from FILE
INFO:  Creating new session
INFO:  =====   Server: https://us-west-2a.online.tableau.com
INFO:  =====   Username: jfitzgerald@tableau.com
INFO:  Tableau Server Site: alpodev
INFO:  Connecting to the server...
INFO:  Succeeded
INFO:
403069: Forbidden
Sites query is unsupported for Tableau Cloud.
=> Fix error output of listsites

.gitignore, src/commands/datasources_and_workbooks/publish_command.py
get the project id instead of the project object reference
=> TFS 1428581 publish project

tabcmd/commands/auth/session.py, tabcmd/commands/constants.py, tabcmd/commands/datasources_and_workbooks/get_url_command.py, tabcmd/execution/__init__.py, tabcmd/execution/logger_config.py, tabcmd/execution/parent_parser.py, tabcmd/execution/tabcmd_controller.py
- added a new level of logging for debugging
- fixed geturl behavior when the url was wrongly formatted
=> Trace logging and bug fix

tabcmd/commands/server.py
Add in this small fix before cutting a release.
=> call sites endpoint correctly

.gitignore, tabcmd/commands/datasources_and_workbooks/export_command.py, tabcmd/commands/datasources_and_workbooks/get_url_command.py, tabcmd/commands/server.py, tabcmd/execution/global_options.py, tabcmd/execution/localize.py, tests/commands/test_geturl_utils.py, tests/parsers/common_setup.py, tests/parsers/test_parser_add_user.py, tests/parsers/test_parser_create_site_users.py, tests/parsers/test_parser_create_user.py, tests/parsers/test_parser_delete_site_user.py, tests/parsers/test_parser_remove_user.py
Fixes #199 
tested on csv files with and without BOM
=> open csv files allowing for BOM

docs/index.md
Hi Jac. Does this note address the issue?
=> Issue-226: escape character note added for logging in

docs/index.md, docs/tabcmd_cmd.md
I put the note in the get and the export sections. Still looking for a place in the REST API docs to place the note as well.
=> Scotm 1436186

.gitignore, docs/tabcmd_cmd.md
New functional behavior added for tabcmd 2
#244 
#254
=> Docs update: list command, filter syntax

.gitignore, pyproject.toml, tabcmd/commands/datasources_and_workbooks/publish_command.py, tests/assets/detailed_users.csv, tests/e2e/online_tests.py
adds in more test cases, and support for alternating between tabcmd 2 and tabcmd classic installations
=> Improved support for tabcmd testing

docs/tabcmd_cmd.md
=> Add details to list command

_includes/footer.html, _includes/head.html, assets/css/main.css
Adding the cookie manager and OneTrust code so we can collect Google Analytics data (GA4).
Added Cookie manager to footer
Updated footer links and CSS styles
=> @gus W-17274770 Add Cookie Manager and links

res/metadata.yml
=> fix: Show correct version in windows file properties

tabcmd/commands/auth/session.py, tabcmd/commands/datasources_and_workbooks/datasources_and_workbooks_command.py, tabcmd/commands/datasources_and_workbooks/export_command.py, tabcmd/locales/de/tabcmd_messages_de.properties, tabcmd/locales/en/tabcmd_messages_en.properties, tabcmd/locales/es/tabcmd_messages_es.properties, tabcmd/locales/fr/tabcmd_messages_fr.properties, tabcmd/locales/ga/tabcmd_messages_ga.properties, tabcmd/locales/it/tabcmd_messages_it.properties, tabcmd/locales/ja/tabcmd_messages_ja.properties, tabcmd/locales/ko/tabcmd_messages_ko.properties, tabcmd/locales/pt/tabcmd_messages_pt.properties, tabcmd/locales/sv/tabcmd_messages_sv.properties, tabcmd/locales/zh/tabcmd_messages_zh.properties, tests/commands/test_datasources_and_workbooks_command.py, tests/commands/test_geturl_utils.py, tests/commands/test_session.py, tests/e2e/online_tests.py, tests/e2e/setup_e2e.py
Fixing the below issues: 
#346 
#347
#349 
Fix for test failures with e2e/online_tests.py runs
=> Fix for #346 & #347
