- contributing.md
- setup.cfg
- setup.py
I hadn't realized this is where the 80 column limit was coming from. I put 120 without much thought - would also be ok with 100? Anyone have strong opinions?
Any other rules people would like added or turned off while we're thinking about it? This page seems to cover the options: https://www.mankier.com/1/pycodestyle
> proposed: change max line length in pycodestyle, document it

- tabcmd/commands/datasources_and_workbooks/delete_command.py
- tabcmd/commands/group/create_group_command.py
- tabcmd/commands/group/delete_group_command.py
- tabcmd/commands/project/create_project_command.py
- tabcmd/parsers/create_group_parser.py
- tabcmd/parsers/delete_parser.py
- tabcmd/parsers/delete_project_parser.py
- tests/commands/test_run_commands.py
- tests/test_parser_create_group.py
- tests/test_parser_delete.py
1. Deletegroup: https://github.com/tableau/tabcmd/issues/24
- Tabcmd2 "delete group" command contains flag --name as group name. To delete a group Tabcmd2 uses `tabcmd deletegroup --name "ExampleGroup"`. Original Tabcmd does not use --name flag. Updated the command code accordingly.
2. Deleteproject: https://github.com/tableau/tabcmd/issues/26
- Tabcmd2 "deleteproject" command contains flag --name as project name. To delete a project Tabcmd2 uses tabcmd depeteproject --name "ExampleProject". Tabcmd does not use --name flag. Updated the command code accordingly.
3.  Delete: https://github.com/tableau/tabcmd/issues/49
- Tabcmd2 requires user to specify workbook using flag —workbook for deleting a workbook where as in the existing Tabcmd user can either use —workbook flag OR send name of …
> Fixed Command bugs: CreateGroup, DeleteGroup, DeleteProject, Delete

- .github/workflows/run-tests.yml
I see right now it only triggers on actually pushes. Probably worth trigger on pull requests and being explicit about the target branch(es)
> Trigger CI on Pull Request

- tabcmd/__main__.py
This makes it so you can just run `python -m tabcmd` and get the CLI to work. I *think* that should make the instructions for local development a lot easier to understand. 
Its also often a better end user experience to qualify the tabcmd calls with the python executable; if users have multiple Pythons installed on their system it makes it more explicit which one is actually invoicing tabcmd
> PEP338 Support - Execute Module as Script

- tests/commands/test_run_commands.py
- tests/test_logout_parser.py
- tests/test_parser_create_extracts.py
- tests/test_parser_create_group.py
- tests/test_parser_create_project.py
- tests/test_parser_create_site_users.py
- tests/test_parser_create_user.py
- tests/test_parser_decrypt_extracts.py
- tests/test_parser_delete.py
- tests/test_parser_delete_extracts.py
- tests/test_parser_delete_group.py
- tests/test_parser_delete_site_user.py
- tests/test_parser_edit_site.py
- tests/test_parser_encrypt_extracts.py
- tests/test_parser_export.py
- tests/test_parser_get_url.py
- tests/test_parser_list_sites.py
- tests/test_parser_login.py
- tests/test_parser_publish.py
- tests/test_parser_publish_samples.py
- tests/test_parser_reencrypt_extracts.py
- tests/test_parser_runschedule.py
The standard library has had mock as part of unittest since Python 3.3, so no reason now to wrap it with a try...except block.
A lot of these weren't really used though, so deleted where it didn't matter
> Mock Import Cleanup

- src/commands/auth/session.py
New output: a) with valid account for default site
Creating new session
=====   Server: http://near-win1.tsi.lan
=====   Username: jfitzgerald
Tableau Server Site: Default Site
Connecting to the server...
Succeeded
b) with invalid account for default site
=====   Server: http://near-win1.tsi.lan
=====   Username: jfitzgerald
Tableau Server Site: Default Site
Connecting to the server...
401001: Signin Error
Error signing in to Tableau Server
> Defect 1426854: [Tabcmd WAM] Login doesn't fail graciously with clear errors when the site is missing

- tabcmd.py
- tabcmd/commands/site/list_command.py
- tabcmd/commands/site/list_sites_command.py
- tabcmd/execution/map_of_commands.py
- tests/e2e/online_tests.py
I created this because I kept having to open up a site to see project/workbook names to call commands on :) 
Usage: tabcmd **list** _content_type_
content_type currently supports the options projects | workbooks | datasources
Display is modelled on listsites
example:
Creating new session
=====   Server: https://cd-near.online.dev.tabint.net/
=====   Username: jac.fitzgerald@salesforce.com
Tableau Server Site: cdnearcoresvcsauth
Connecting to the server...
Succeeded
===== Listing projects content for user jac.fitzgerald@salesforce.com...
NAME: default
ID: fb6171a2-acc0-4a3c-8cff-22962d7b45ee
NAME: Samples
ID: cf0e3d2f-82a0-4d9f-b1b5-9b03fff72064
NAME: Admin Insights
ID: de529fef-5c50-4dad-97a1-b31829278012
NAME: test
ID: 330d5e95-7818-48c4-ac92-ac7d79f9040b
NAME: Project1
ID: …
> Add command to list items of a given content type

- tabcmd/commands/datasources_and_workbooks/export_command.py
- tabcmd/execution/logger_config.py
- tests/commands/test_geturl_utils.py
- tests/commands/test_run_commands.py
- tests/e2e/online_tests.py
1. updated export command to look for filter params on the url given and convert them to RequestOption view_filters
2. fixed bytes v iterator for data files.
3. added tests
> make export use filters, add tests

- tabcmd/commands/group/delete_group_command.py
- tabcmd/commands/server.py
- tabcmd/commands/user/delete_site_users_command.py
- tabcmd/commands/user/user_data.py
- tests/e2e/online_tests.py
Current status
1. publish_samples fails with permissions error on project? Looks like the tsc error we've been seeing.
2. extracts tests fail b/c the workbooks use an MS Access connection
3. Added a lot of info when add users to site/etc fail.
> Fix some e2e tests

- tabcmd/commands/auth/session.py
- tabcmd/commands/datasources_and_workbooks/datasources_and_workbooks_command.py
- tabcmd/commands/datasources_and_workbooks/export_command.py
- tabcmd/commands/datasources_and_workbooks/get_url_command.py
- tabcmd/commands/user/user_data.py
- tabcmd/execution/logger_config.py
- tests/commands/test_geturl_utils.py
- tests/e2e/online_tests.py
- refresh parameter is used to set maxAge
- filters can be set either with --filter option or in url parameters
- Height/width parameters are not yet implemented, b/c they are not available in the underlying REST API
- orientation can be set in _get_ command
> Implement command line and url parameters for get/export

- tabcmd/commands/auth/session.py
- tabcmd/execution/localize.py
The error message was too specific: made it generic for any missing argument and added a tip to see the argument options. New output:
c:\dev\tabcmd2>tabcmd listsites
logging: INFO
constants.py: Cannot sign in because of missing arguments: Run 'tabcmd login -h' for details on required arguments
> tfs 1427025: Confusing error message related to sign-in

- tabcmd/commands/auth/session.py
- tabcmd/execution/localize.py
old: said username/token was missing even when it was there
c:\dev\tabcmd2>python -m tabcmd login -u jfitzgerald@tableau.com
constants.py: Cannot sign in because of missing arguments: Either a ''username'' option or a ''token'' option must be specified
new: says some arguments are missing, see help for info on required args
c:\dev\tabcmd2>python -m tabcmd login -u jfitzgerald@tableau.com
constants.py: Cannot sign in because of missing arguments: Run 'tabcmd login -h' for details on required arguments
> Improve confusing help message for signing in

- tabcmd/execution/global_options.py
- tests/commands/test_execution.py
also renamed some tests for easier reading
> extract encryption defaults to false

- tabcmd/commands/datasources_and_workbooks/datasources_and_workbooks_command.py
- tabcmd/commands/datasources_and_workbooks/get_url_command.py
- tabcmd/commands/project/delete_project_command.py
- tabcmd/locales/en/tabcmd_messages_en.properties
- tests/commands/test_geturl_utils.py
- tests/e2e/language_tests.py
- tests/e2e/online_tests.py
this simply adds datasources as an option for the Get command, in addition to the existing views and workbooks.
> Add Datasources to the Get Command

- tabcmd/commands/datasources_and_workbooks/export_command.py
- tabcmd/commands/datasources_and_workbooks/get_url_command.py
- tabcmd/commands/user/create_site_users.py
- tabcmd/commands/user/create_users_command.py
- tabcmd/commands/user/user_data.py
- tabcmd/execution/global_options.py
- tests/commands/test_run_commands.py
Fixes https://github.com/tableau/tabcmd/issues/197
There is an underlying bug in tsc that doesn't accept all values of auth-type. That will be fixed and once the new version of tsc is being used, it will work here too.
example:
tabcmd createsiteusers "tests\assets\detailed_users.csv" --role Viewer
tabcmd createsiteusers "tests\assets\detailed_users.csv" --auth-type SAML
> add role and auth args

- tabcmd/execution/tabcmd_controller.py
When people ask for help they usually show default logs and don't know what version they have. This will make it easier to debug.
> Always log version

- pyproject.toml
- tabcmd/__main__.py
- tabcmd/commands/auth/session.py
- tabcmd/execution/parent_parser.py
- tests/commands/test_session.py
Allow the user to set proxy information for tabcmd, or to unset it (--no-proxy)
Also allow the user to set a certificate, but this feature should be considered beta in this release.
> proxy settings

- pyproject.toml
should fix embedding pipeline, which was pulling in new version 0.26 of tsc
> freeze tsc dependency

- tabcmd/commands/auth/session.py
- tests/commands/test_session.py
You could previously put a token value in --password-file if you also passed in --token-name, but this is much clearer and makes it easier for users to discover and use the option.
> add --token-file option

- pyproject.toml
* freeze tsc dependency to 0.25
(cherry picked from commit fc992e4a8b4e82e8d5034fe6db8f8b21e5a9e4bb)
main and development need to be reconciled, I don't want to block this fix on it.
> freeze tsc dependency (#248)

- tabcmd/commands/datasources_and_workbooks/publish_command.py
- tabcmd/commands/site/list_command.py
- tests/commands/test_publish_command.py
- tests/commands/test_run_commands.py
- tests/commands/test_session.py
> fix log error on publish

- tabcmd/commands/datasources_and_workbooks/get_url_command.py
- tabcmd/commands/datasources_and_workbooks/publish_command.py
- tests/commands/test_execution.py
- tests/commands/test_geturl_utils.py
- tests/commands/test_session.py
- tests/e2e/online_tests.py
@W-13757625 - the command threw an error and failed if the filepath to save to contained a full stop, e.g
c:\users\chevy.chase\
Fixed by using os.path instead of manual parsing. Also added a test to cover the scenario.
> fix filepath handling in Get command

- .github/workflows/package.yml
- .github/workflows/run-tests.yml
- tabcmd-mac.spec
**Issue:** "This application can't be opened" error was encountered on using the tabcmd.app on Mac environment from release artifacts
**Resolution:** The app wasn't properly bundled and the zip of the bundle associated with `actions/upload-artifact@v4` github action led to [loss of executable file's `+x` permission](https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss) and eventually led to aforementioned error while using the app. This PR addresses this issue by tar-ing the app bundle before uploading it to artifact thereby preserving the necessary file permissions
> Fix for "this application can't be opened" error on opening tabcmd.app on Mac

- pyproject.toml
`argparse` is a [Python standard module](https://docs.python.org/3/library/argparse.html) (Python > 3.2).
> Remove argparse

- .gitignore
- README.md
- contributing.md
- pyproject.toml
- res/README.md
- tabcmd-windows.spec
Building with pyinstaller v6 caused the executable to trigger automated malware alerts. Changing back to build with v5.13 gets an almost clean scan. 
tabcmd 0.13 from github built with pyinstaller 6.x: ~30 vendors flagged it
https://www.virustotal.com/gui/file/829b092e47228c0cea2c54e0f75e63501b5e12135a76fef2dcbaba2deac228ed
my freshly built copy of 0.13 with pyinstaller 5.13: 2 vendors flagged it
https://www.virustotal.com/gui/file/b1c8be24ade44a8eae93e6a03d56fcd99caf389549c647fcb133b965d1c8e1f4/detection
tabcmd0.11.exe from github: was also built with 5.13: 1 vendor flaggged it
https://www.virustotal.com/gui/file/f6453b2549b9f696701e76d83b7c349a8710d3492a4fabf3029a6634c7f236f2
> packaging update

- tabcmd/commands/user/user_data.py
- tests/parsers/test_parser_create_site_users.py
Completes https://github.com/tableau/tabcmd/issues/288
> add auth type TableauIDWithMFA

- tabcmd/commands/server.py
- tabcmd/execution/parent_parser.py
- tabcmd/execution/tabcmd_controller.py
- tests/commands/test_projects_utils.py
- tests/commands/test_publish_command.py
- tests/commands/test_run_commands.py
- tests/commands/test_server.py
This pull request includes significant changes to the `get_items_by_name` function in `tabcmd/commands/server.py` to support pagination and improve item retrieval. Additionally, comprehensive unit tests have been added to ensure the function's correctness under various scenarios.
> Fix for not retrieving all items when response has multiple pages of items

- tabcmd/commands/server.py
- tests/commands/test_server.py
I pushed the parent-project filter into the request so we only get the results that match, this means the result we want will always be on the first page (and will coincidentally improve performance of most queries by some extent)
We should rename this method [and others] to make it clear they will return exactly one item or throw an error.
> fix for error when item is not in first page

- pyproject.toml
Simple library bump. This enables many necessary options like incremental publishing. 
https://github.com/tableau/server-client-python/releases/tag/v0.35
> Update tsc library to newest: 0.35

- tabcmd/commands/datasources_and_workbooks/publish_command.py
> fix: error in publish command

- tabcmd/execution/parent_parser.py
- tabcmd/execution/tabcmd_controller.py
e.g "tabcmd --server --site --..."  would throw an exception about not having an attribute.
Now it will print out the usage information.
> Improve error when run with no command given

- tabcmd/commands/datasources_and_workbooks/export_command.py
- tests/e2e/online_tests.py
Fixes #233 
example:
tabcmd export SampleWorkbook/Sheet1?Product%20Type=Tea   --fullpdf --pagelayout landscape
OR (new command format option, same output)
tabcmd export SampleWorkbook/Sheet1 --filter" "Product Type=Tea" --fullpdf --pagelayout landscape
> Enable filtering when an entire workbook is exported

- tabcmd/commands/datasources_and_workbooks/datasources_and_workbooks_command.py
- tabcmd/commands/datasources_and_workbooks/export_command.py
- tabcmd/commands/datasources_and_workbooks/get_url_command.py
- tests/commands/test_datasources_and_workbooks_command.py
- tests/e2e/online_tests.py
(This PR is built on top of the open workbook filtering PR)
This now supports the get command with url params ?:size=x,y
and the export command with options --height, --weight
closes #94
> Enable setting export image sizes 

- tabcmd/commands/datasources_and_workbooks/datasources_and_workbooks_command.py
- tests/commands/test_datasources_and_workbooks_command.py
Adding the specified height & width options to the export PDF's request
> Exporting pdf with height & width options not working as intended

- pyproject.toml
- tabcmd/commands/extracts/refresh_extracts_command.py
- tests/commands/test_run_commands.py
Adding support for incremental extract refresh
> Adding support for incremental extract refresh
